#@data/values-schema
---

#@schema/desc "The namespace where Cert Manager is deployed."
#@schema/validation min_len=1
namespace: cert-manager

#@schema/desc "Settings for Let's Encrypt."
letsencrypt:
  #@schema/desc "Whether to include a ClusterIssuer for Let's Encrypt."
  include: false
  #@schema/desc "Whether to use Let's Encrypt staging, recommended for non-production environments."
  staging: true
