apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cert-manager-issuers.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: cert-manager-issuers.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cert-manager-issuers/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cert-manager-issuers.packages.kadras.io
spec:
  categories:
  - certificate-management
  - security
  - tls
  displayName: cert-manager-issuers
  longDescription: A collection of ClusterIssuers to use with cert-manager, including
    a private CA and optional Let's Encrypt support.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: A collection of ClusterIssuers to use with cert-manager.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/cert-manager-issuers
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cert-manager-issuers
spec:
  packageRef:
    refName: cert-manager-issuers.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
